// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace mainServer.schemas.FMessage
{

public enum FMessageType : sbyte
{
  StartGame = 0,
  LeaveRoom = 1,
};


}
