// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Upzp.GameStatus
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

/// Postion on the planet, represented by
/// geographic coordinates.
public struct Position : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Position __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Longitude { get { return __p.bb.GetDouble(__p.bb_pos + 0); } }
  public double Latitude { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }

  public static Offset<Upzp.GameStatus.Position> CreatePosition(FlatBufferBuilder builder, double Longitude, double Latitude) {
    builder.Prep(8, 16);
    builder.PutDouble(Latitude);
    builder.PutDouble(Longitude);
    return new Offset<Upzp.GameStatus.Position>(builder.Offset);
  }
};


}
