// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UPZP.FWaitingRoom
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FTeam : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static FTeam GetRootAsFTeam(ByteBuffer _bb) { return GetRootAsFTeam(_bb, new FTeam()); }
  public static FTeam GetRootAsFTeam(ByteBuffer _bb, FTeam obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FTeam __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UPZP.FWaitingRoom.FClient? Clients(int j) { int o = __p.__offset(4); return o != 0 ? (UPZP.FWaitingRoom.FClient?)(new UPZP.FWaitingRoom.FClient()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ClientsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<UPZP.FWaitingRoom.FTeam> CreateFTeam(FlatBufferBuilder builder,
      VectorOffset clientsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FTeam.AddClients(builder, clientsOffset);
    return FTeam.EndFTeam(builder);
  }

  public static void StartFTeam(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddClients(FlatBufferBuilder builder, VectorOffset clientsOffset) { builder.AddOffset(0, clientsOffset.Value, 0); }
  public static VectorOffset CreateClientsVector(FlatBufferBuilder builder, Offset<UPZP.FWaitingRoom.FClient>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateClientsVectorBlock(FlatBufferBuilder builder, Offset<UPZP.FWaitingRoom.FClient>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartClientsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<UPZP.FWaitingRoom.FTeam> EndFTeam(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UPZP.FWaitingRoom.FTeam>(o);
  }
};


}
