// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Upzp.GameStatus
{

/// Possible vehicles for a player.
public enum Vehicle : sbyte
{
  Pedestrian = 0,
  Cyclist = 1,
  Car = 2,
};


}
