// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace mainServer.schemas.FClientId
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FClientId : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static FClientId GetRootAsFClientId(ByteBuffer _bb) { return GetRootAsFClientId(_bb, new FClientId()); }
  public static FClientId GetRootAsFClientId(ByteBuffer _bb, FClientId obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FClientId __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<mainServer.schemas.FClientId.FClientId> CreateFClientId(FlatBufferBuilder builder,
      int id = 0) {
    builder.StartTable(1);
    FClientId.AddId(builder, id);
    return FClientId.EndFClientId(builder);
  }

  public static void StartFClientId(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static Offset<mainServer.schemas.FClientId.FClientId> EndFClientId(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<mainServer.schemas.FClientId.FClientId>(o);
  }
  public static void FinishFClientIdBuffer(FlatBufferBuilder builder, Offset<mainServer.schemas.FClientId.FClientId> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFClientIdBuffer(FlatBufferBuilder builder, Offset<mainServer.schemas.FClientId.FClientId> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
