// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace mainServer.schemas.FGameStarted
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FGameStarted : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static FGameStarted GetRootAsFGameStarted(ByteBuffer _bb) { return GetRootAsFGameStarted(_bb, new FGameStarted()); }
  public static FGameStarted GetRootAsFGameStarted(ByteBuffer _bb, FGameStarted obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FGameStarted __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Ip { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIpBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIpBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIpArray() { return __p.__vector_as_array<byte>(4); }
  public int Port { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<mainServer.schemas.FGameStarted.FGameStarted> CreateFGameStarted(FlatBufferBuilder builder,
      StringOffset ipOffset = default(StringOffset),
      int port = 0) {
    builder.StartTable(2);
    FGameStarted.AddPort(builder, port);
    FGameStarted.AddIp(builder, ipOffset);
    return FGameStarted.EndFGameStarted(builder);
  }

  public static void StartFGameStarted(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddIp(FlatBufferBuilder builder, StringOffset ipOffset) { builder.AddOffset(0, ipOffset.Value, 0); }
  public static void AddPort(FlatBufferBuilder builder, int port) { builder.AddInt(1, port, 0); }
  public static Offset<mainServer.schemas.FGameStarted.FGameStarted> EndFGameStarted(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<mainServer.schemas.FGameStarted.FGameStarted>(o);
  }
  public static void FinishFGameStartedBuffer(FlatBufferBuilder builder, Offset<mainServer.schemas.FGameStarted.FGameStarted> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFGameStartedBuffer(FlatBufferBuilder builder, Offset<mainServer.schemas.FGameStarted.FGameStarted> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
