// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace mainServer.schemas.FWaitingRoom
{

public enum FVehicleType : sbyte
{
  Pedestrian = 0,
  Cyclist = 1,
  Car = 2,
};


}
